name: Publish Log4brains
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Log4brains
        run: npm install -g log4brains
      - name: Debug Pre-Build
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Config file contents:"
          cat .log4brains.yml
          echo "ADR directory contents:"
          ls -la docs/adr/
      - name: Build Log4brains Site
        run: log4brains build --verbose --basePath /fc-madr/log4brains
      - name: Debug Post-Build
        run: |
          echo "Log4brains directory:"
          ls -la .log4brains || echo ".log4brains directory does not exist"
          echo "Output directory:"
          ls -la .log4brains/out || echo ".log4brains/out directory does not exist"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .log4brains/out
          target-folder: log4brains
          commit-message: 'Deploy Log4brains site 🚀'
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}